# see: https://doc.rust-lang.org/cargo/reference/config.html
[profile.dev]
opt-level = 0
debug = true
# split-debuginfo = 'off'  # Platform-specific. (`off`, `packed`, or `unpacked`) https://doc.rust-lang.org/rustc/codegen-options/index.html#split-debuginfo
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
# 2 or 3 for speed; 's' or 'z' for size optimization.
opt-level = 3       # Optimize for speed
lto = true          # Enable Link Time Optimization  (true = same as "fat")
codegen-units = 1   # Reduce number of codegen units to increase optimizations.
#debug = true        # only for flamegraph
incremental = true  # Incremental compilation
